---
#   Copyright 2022 IBM Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

##########################################################################
# tasks file for sap_opsyscheck_dir_mounted_managed_node free space check
############################################################################


- name: Set variable for mounts
  set_fact:
    sap_opsyscheck_mounts_managed_node: "{{ ansible_mounts | map(attribute='mount') | list}}"



###
### Check that /usr/sap has at least 10 GB free disk space
###
- name: Warning if /usr/sap is not a separate file system
  debug:
    msg: "WARNING: /usr/sap is not a separate file system"
  when: "'/usr/sap' not in sap_opsyscheck_mounts_managed_node"

- name: Get status of /usr/sap
  stat:
    path: "/usr/sap"
    follow: "yes"
  register: sap_opsyscheck_stat_data_usr_sap

- name: Set flag if /usr/sap exists, is a directory and is readable
  set_fact:
    sap_opsyscheck_dir_exists_usr_sap: "{{ sap_opsyscheck_stat_data_usr_sap.stat.exists  and  sap_opsyscheck_stat_data_usr_sap.stat.isdir  and  sap_opsyscheck_stat_data_usr_sap.stat.readable }}"

- name: Print warning if /usr/sap does not exist or is not a directory or is not readable
  debug:
    msg: "WARNING: '/usr/sap' either does not exist or is not a directory or not readable"
  when: not sap_opsyscheck_dir_exists_usr_sap|bool

- name: Determine free disk space for /usr/sap
  shell: "cd /usr/sap && df -m . | grep '/' | awk '{ print $3}'"
  register: sap_opsyscheck_tmp_MB_free_output
  when: sap_opsyscheck_dir_exists_usr_sap|bool

- name: Set integer variable for MBytes free
  set_fact:
    sap_opsyscheck_MB_free_in_usr_sap: "{{ sap_opsyscheck_tmp_MB_free_output.stdout | int }}"
  when: sap_opsyscheck_dir_exists_usr_sap|bool



###
### Check that /sapmnt  has at least  5 GB free disk space
###
- name: Warning if /sapmnt is not a separate file system
  debug:
    msg: "WARNING: /sapmnt is not a separate file system"
  when: "'/sapmnt' not in sap_opsyscheck_mounts_managed_node"

- name: Get status of /sapmnt
  stat:
    path: "/sapmnt"
    follow: "yes"
  register: sap_opsyscheck_stat_data_sapmnt

- name: Set flag if /sapmnt exists, is a directory and is readable
  set_fact:
    sap_opsyscheck_dir_exists_sapmnt: "{{ sap_opsyscheck_stat_data_sapmnt.stat.exists  and  sap_opsyscheck_stat_data_sapmnt.stat.isdir  and  sap_opsyscheck_stat_data_sapmnt.stat.readable }}"

- name: Print warning if /sapmnt does not exist or is not a directory or is not readable
  debug:
    msg: "WARNING: '/sapmnt' either does not exist or is not a directory or not readable"
  when: not sap_opsyscheck_dir_exists_sapmnt|bool

- name: Determine free disk space for /sapmnt
  shell: "cd /sapmnt && df -m . | grep '/' | awk '{ print $3}'"
  register: sap_opsyscheck_tmp_MB_free_output
  when: sap_opsyscheck_dir_exists_sapmnt|bool

- name: Set integer variable for MBytes free
  set_fact:
    sap_opsyscheck_MB_free_in_sapmnt: "{{ sap_opsyscheck_tmp_MB_free_output.stdout | int }}"
  when: sap_opsyscheck_dir_exists_sapmnt|bool



###
### Check that /db2     has at least 50 GB free disk space
###
- name: Warning if /db2 is not a separate file system
  debug:
    msg: "WARNING: /db2 is not a separate file system"
  when: "'/db2' not in sap_opsyscheck_mounts_managed_node"

- name: Get status of /db2
  stat:
    path: "/db2"
    follow: "yes"
  register: sap_opsyscheck_stat_data_db2

- name: Set flag if /db2 exists, is a directory and is readable
  set_fact:
    sap_opsyscheck_dir_exists_db2: "{{ sap_opsyscheck_stat_data_db2.stat.exists  and  sap_opsyscheck_stat_data_db2.stat.isdir  and  sap_opsyscheck_stat_data_db2.stat.readable }}"

- name: Print warning if /db2 does not exist or is not a directory or is not readable
  debug:
    msg: "WARNING: '/db2' either does not exist or is not a directory or not readable"
  when: not sap_opsyscheck_dir_exists_db2|bool

- name: Determine free disk space for /db2
  shell: "cd /db2 && df -m . | grep '/' | awk '{ print $3}'"
  register: sap_opsyscheck_tmp_MB_free_output
  when: sap_opsyscheck_dir_exists_db2|bool

- name: Set integer variable for MBytes free
  set_fact:
    sap_opsyscheck_MB_free_in_db2: "{{ sap_opsyscheck_tmp_MB_free_output.stdout | int }}"
  when: sap_opsyscheck_dir_exists_db2|bool



###
### Check that /tmp     has at least  2 GB free disk space
###
- name: Warning if /tmp is not a separate file system
  debug:
    msg: "WARNING: /tmp is not a separate file system"
  when: "'/tmp' not in sap_opsyscheck_mounts_managed_node"

- name: Get status of /tmp
  stat:
    path: "/tmp"
    follow: "yes"
  register: sap_opsyscheck_stat_data_tmp

- name: Set flag if /tmp exists, is a directory and is readable
  set_fact:
    sap_opsyscheck_dir_exists_tmp: "{{ sap_opsyscheck_stat_data_tmp.stat.exists  and  sap_opsyscheck_stat_data_tmp.stat.isdir  and  sap_opsyscheck_stat_data_tmp.stat.readable }}"

- name: Print warning if /tmp does not exist or is not a directory or is not readable
  debug:
    msg: "WARNING: '/tmp' either does not exist or is not a directory or not readable"
  when: not sap_opsyscheck_dir_exists_tmp|bool

- name: Determine free disk space for /tmp
  shell: "cd /tmp && df -m . | grep '/' | awk '{ print $3}'"
  register: sap_opsyscheck_tmp_MB_free_output
  when: sap_opsyscheck_dir_exists_tmp|bool

- name: Set integer variable for MBytes free
  set_fact:
    sap_opsyscheck_MB_free_in_tmp: "{{ sap_opsyscheck_tmp_MB_free_output.stdout | int }}"
  when: sap_opsyscheck_dir_exists_tmp|bool



###
### Check that /var     has at least  3 GB free disk space
###
- name: Warning if /var is not a separate file system
  debug:
    msg: "WARNING: /var is not a separate file system"
  when: "'/var' not in sap_opsyscheck_mounts_managed_node"

- name: Get status of /var
  stat:
    path: "/var"
    follow: "yes"
  register: sap_opsyscheck_stat_data_var

- name: Set flag if /var exists, is a directory and is readable
  set_fact:
    sap_opsyscheck_dir_exists_var: "{{ sap_opsyscheck_stat_data_var.stat.exists  and  sap_opsyscheck_stat_data_var.stat.isdir  and  sap_opsyscheck_stat_data_var.stat.readable }}"

- name: Print warning if /var does not exist or is not a directory or is not readable
  debug:
    msg: "WARNING: '/var' either does not exist or is not a directory or not readable"
  when: not sap_opsyscheck_dir_exists_var|bool

- name: Determine free disk space for /var
  shell: "cd /var && df -m . | grep '/' | awk '{ print $3}'"
  register: sap_opsyscheck_tmp_MB_free_output
  when: sap_opsyscheck_dir_exists_var|bool

- name: Set integer variable for MBytes free
  set_fact:
    sap_opsyscheck_MB_free_in_var: "{{ sap_opsyscheck_tmp_MB_free_output.stdout | int }}"
  when: sap_opsyscheck_dir_exists_var|bool



###
### The reporting section
###

- name: Report free disk space for /usr/sap (in GB)
  debug:
    msg: "{{ '{:0.2f}'.format(sap_opsyscheck_MB_free_in_usr_sap|int/1024) }} GB available in /usr/sap"
  when: sap_opsyscheck_dir_exists_usr_sap|bool

- name: Report free disk space for /sapmnt (in GB)
  debug:
    msg: "{{ '{:0.2f}'.format(sap_opsyscheck_MB_free_in_sapmnt|int/1024) }} GB available in /sapmnt"
  when: sap_opsyscheck_dir_exists_sapmnt|bool

- name: Report free disk space for /db2 (in GB)
  debug:
    msg: "{{ '{:0.2f}'.format(sap_opsyscheck_MB_free_in_db2|int/1024) }} GB available in /db2"
  when: sap_opsyscheck_dir_exists_db2|bool

- name: Report free disk space for /tmp (in GB)
  debug:
    msg: "{{ '{:0.2f}'.format(sap_opsyscheck_MB_free_in_tmp|int/1024) }} GB available in /tmp"
  when: sap_opsyscheck_dir_exists_tmp|bool

- name: Report free disk space for /var (in GB)
  debug:
    msg: "{{ '{:0.2f}'.format(sap_opsyscheck_MB_free_in_var|int/1024) }} GB available in /var"
  when: sap_opsyscheck_dir_exists_var|bool



###
### The check section
###

- name: Check that /usr/sap has at least 10 GB free disk space
  debug:
    msg: "ERROR: Less than 10 GB free disk space in directory /usr/sap"
  when: "sap_opsyscheck_dir_exists_usr_sap|bool and sap_opsyscheck_MB_free_in_usr_sap|int < 10*1024"

- name: Check that /sapmnt has at least 5 GB free disk space
  debug:
    msg: "ERROR: Less than 5 GB free disk space in directory /sapmnt"
  when: "sap_opsyscheck_dir_exists_sapmnt|bool and sap_opsyscheck_MB_free_in_sapmnt|int < 5*1024"

- name: Check that /db2 has at least 50 GB free disk space
  debug:
    msg: "ERROR: Less than 50 GB free disk space in directory /db2"
  when: "sap_opsyscheck_dir_exists_db2|bool and sap_opsyscheck_MB_free_in_db2|int < 50*1024"

- name: Check that /tmp has at least 2 GB free disk space
  debug:
    msg: "ERROR: Less than 2 GB free disk space in directory /tmp"
  when: "sap_opsyscheck_dir_exists_tmp|bool and sap_opsyscheck_MB_free_in_tmp|int < 2*1024"

- name: Check that /var has at least 3 GB free disk space
  debug:
    msg: "ERROR: Less than 3 GB free disk space in directory /var"
  when: "sap_opsyscheck_dir_exists_var|bool and sap_opsyscheck_MB_free_in_var|int < 3*1024"

